name: jacksphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d0b'
    - '#4d341e'
    - '#6c4824'
    - '#2f3d48'
    - '#435f6d'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
